# Input
payment_dir: src/payments
order_dir: src/orders
info_dir: src/infos
invoice_dir: src/invoices
import_dir: imports

# Output
dist: dist
invoice_file: invoices.pdf
json_file: data.json

# Day ranges
payment_order_range: 1
